TARGETS = mp3test initresource reserve release infotoadd notifyadd checkneeded init \
	getsamplerate getbitrate getchannel getmpegversion getmaxoutput getloopnum setloopnum \
	getframenum getsumdecoded stream
EXTRA_OBJS = mp3-imports.o shared.o
EXTRA_LIBS = -lpspaudio -lpspmp3 -lstdc++ -lc

COMMON_DIR = ../../../common
include $(COMMON_DIR)/common.mk
